sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t kiyoakim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiyoakim/docker-react npm run test