sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t kiyoakim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiyoakim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-west-2-211292201024"
  bucket-path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"